### ISSUE TITLE
SymDict interferes with the Dict constructor

### ISSUE THREAD

**Issue by cstjean** [samoconnor/SymDict.jl#1]
``` julia
Dict{Symbol, Any}(Dict{Any, Any}(:x=>3))
```

returns a `Dict{Symbol, Any}` but 

``` julia
using SymDict
Dict{Symbol, Any}(Dict{Any, Any}(:x=>3))
```

returns a `Dict{Any, Any}`

**Comment by samoconnor** [comment]
Thanks @cstjean

**Comment by cstjean** [comment]
Hey, I'm sorry, I think I was not very clear in describing the problem. The issue is that the constructor on [this line](https://github.com/samoconnor/SymDict.jl/blob/master/src/SymDict.jl#L21) shadows the Base constructor for `Dict(::Associative)`. I initially filed an [issue](https://github.com/JuliaLang/julia/issues/17092) on JuliaLang before realizing that the problem from this package. You can reproduce the bug by running the above code in two fresh Julia sessions. `Dict{Symbol, Any}(dict)` should always return a `Dict{Symbol, Any}`, but it doesn't when `SymDict` is imported.

**Comment by samoconnor** [comment]
Hi @cstjean,

I could indeed reproduce the problem you described.
With the fix I made it works for me now:

``` julia
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.2 (2015-12-06 21:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using SymDict


julia> Dict{Symbol, Any}(Dict{Any, Any}(:x=>3))
Dict{Symbol,Any} with 1 entry:
  :x => 3
```

Would you suggest a different fix?

**Comment by cstjean** [comment]
I can reproduce your result, but if I import IJulia first:

``` julia
julia> using IJulia

julia> Dict{Symbol, Any}(Dict{Any, Any}(:x=>3))
Dict{Symbol,Any} with 1 entry:
  :x => 3

julia> using SymDict

julia> Dict{Symbol, Any}(Dict{Any, Any}(:x=>3))
Dict{Any,Any} with 1 entry:
  :x => 3
```

That's really weird.

**Comment by cstjean** [comment]
[New issue](https://github.com/JuliaLang/Compat.jl/issues/242). Sorry for blaming SymDict!
